### ISSUE TITLE
Cannot find module `es-symbol` ... while building Chat example

### ISSUE THREAD

**Issue by srph** [goatslacker/alt#152]
Running `npm run build` as instructed in the chat example gives me this error:

```
Error: Cannot find module 'es-symbol' from '/Users/srph/_/alt/mixins'
    at /Users/srph/_/alt/examples/chat/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/Users/srph/_/alt/examples/chat/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/srph/_/alt/examples/chat/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/srph/_/alt/examples/chat/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/srph/_/alt/examples/chat/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/srph/_/alt/examples/chat/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:99:15)
util.print: Use console.log instead
```
*Ran using OSX Yosemite*.

 Anybody else having the same issue?

**Comment by goatslacker** [comment]
Did you try npm install first?

**Comment by srph** [comment]
Ah, yea, I did. Anybody else having the same issue? I just cloned **alt** half a day ago.

**Comment by goatslacker** [comment]
Just tried a fresh clone and it worked:

```bash
git clone git@github.com:goatslacker/alt.git
cd alt
npm install
cd examples/chat
npm install
npm run build
open index.html
```

**Comment by srph** [comment]
I just realized that I didn't run `npm install` on the root directory of alt.
