### ISSUE TITLE
alt.bootstrap: `TypeError: Cannot read property 'Symbol(...`

### ISSUE THREAD

**Issue by iam4x** [goatslacker/alt#27]
Hi,

I have issue using alt + iso, it keeps throwing me:

```
TypeError: Cannot read property 'Symbol(1424950030126the state container)' of undefined
   at /Users/iam4x/github/es6-react-boilerplate/node_modules/alt/dist/alt.js:224:32
   at Array.forEach (native)
   at setAppState (/Users/iam4x/github/es6-react-boilerplate/node_modules/alt/dist/alt.js:223:20)
   at Alt.bootstrap (/Users/iam4x/github/es6-react-boilerplate/node_modules/alt/dist/alt.js:460:9)
   at module.exports (/Users/iam4x/github/es6-react-boilerplate/server/server.router.jsx:14:7)
   at Layer.handle [as handle_request] (/Users/iam4x/github/es6-react-boilerplate/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/Users/iam4x/github/es6-react-boilerplate/node_modules/express/lib/router/index.js:302:13)
   at /Users/iam4x/github/es6-react-boilerplate/node_modules/express/lib/router/index.js:270:7
   at Function.proto.process_params (/Users/iam4x/github/es6-react-boilerplate/node_modules/express/lib/router/index.js:321:12)
   at next (/Users/iam4x/github/es6-react-boilerplate/node_modules/express/lib/router/index.js:261:10)
```

And the example https://github.com/goatslacker/iso/tree/master/examples/react-router-flux is doing the same.

How can I help?

**Comment by iam4x** [comment]
nvm, figured out by my self.
