### ISSUE TITLE
React-Native support?

### ISSUE THREAD

**Issue by aksonov** [goatslacker/alt#328]
Trying to add stores/actions to my react-native project and got following error:
```
Error: Cannot find package main file for package: /Users/aksonov/Documents/PZ/React/node_modules/react-native/node_modules/react-tools/src
    at DependecyGraph.resolveDependency (/Users/aksonov/Documents/PZ/Pods/React/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js:229:13)
    at /Users/aksonov/Documents/PZ/Pods/React/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js:122:22
    at Array.forEach (native)
    at collect (/Users/aksonov/Documents/PZ/Pods/React/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js:120:25)
    at /Users/aksonov/Documents/PZ/Pods/React/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js:135:9
    at Array.forEach (native)
    at collect (/Users/aksonov/Documents/PZ/Pods/React/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js:120:25)
    at /Users/aksonov/Documents/PZ/Pods/React/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js:135:9
    at Array.forEach (native)
    at collect (/Users/aksonov/Documents/PZ/Pods/React/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js:120:25)
    at /Users/aksonov/Documents/PZ/Pods/React/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js:135:9
    at Array.forEach (native)
    at collect (/Users/aksonov/Documents/PZ/Pods/React/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js:120:25)
    at DependecyGraph.getOrderedDependencies (/Users/aksonov/Documents/PZ/Pods/React/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js:141:3)
    at /Users/aksonov/Documents/PZ/Pods/React/packager/react-packager/src/DependencyResolver/haste/index.js:96:35
    at tryCatcher (/Users/aksonov/Documents/PZ/Pods/React/node_modules/bluebird/js/main/util.js:24:31)
```

**Comment by goatslacker** [comment]
That error looks unrelated to alt

**Comment by 0x80** [comment]
I'm running into the same problem / error and tracked it down to:

const connectToStores = require('alt/utils/connectToStores');

So I don't think this is unrelated to alt... Anything special required to make alt work with react-native?

**Comment by froatsnook** [comment]
I'm running alt with reactive native without any issues! I just npm installed everything.

**Comment by 0x80** [comment]
What versions are you using? 

Really the only thing I have to do to break my app is
```const connectToStores = require('alt/utils/connectToStores');```

I don't get it! :/

**Comment by froatsnook** [comment]
From my package.json:

```javascript
    "alt": "^0.16.10"
    "react-native": "^0.6.0"
```

**Comment by goatslacker** [comment]
Yes this might be an issue. I'll patch it.

**Comment by 0x80** [comment]
@goatslacker great to hear that you're on to something!  I'm using 0.17.1, so I guess there is a difference there.

**Comment by goatslacker** [comment]
No difference. It's just that connectToStores uses React when it should be using react-native.

I'm actually not sure how it works for @froatsnook

**Comment by mltucker** [comment]
I think it's working for me because I call listen and unlisten manually.

**Comment by froatsnook** [comment]
I think it's working for me because I call listen and unlisten manually.

**Comment by goatslacker** [comment]
Requiring the package alone should probably give you an error, since it requires React to build the connectToStores class...again, idk /shrug.

**Comment by 0x80** [comment]
For now I managed to get things working by doing a find/replace of "react" with "react-native" in all of the utils files

**Comment by Emibob** [comment]
Hey @goatslacker I am running into the same issue. Is @0x80 's fix an acceptable solution? Thank you.

**Comment by goatslacker** [comment]
Yup that works well.

**Comment by ppiekarczyk** [comment]
Hello everyone, future everyone who may have an issue with React Native + Alt (and webpack)

If you're using webpack, you can try to set an alias inside resolve:

```javascript
  resolve: {
    alias: {
      'react': 'react-native'
    }
  }
```

https://github.com/mjohnston/react-native-webpack-server/issues/58#issuecomment-139622341

**Comment by BerndWessels** [comment]
Hello

I tried @0x80 fix, but that didn't help.

I don't know how to do @ppiekarczyk fix in a react-native android application?

I get `Uncaught SyntaxError: Unexpected token ILLEGAL` in `alt\lib\index.js : 1`

alt version 0.17.3
react-native version 0.11.0

Please help, thank you
Bernd

**Comment by kingdango** [comment]
I am using OOTB react-native sample app (react-native version 0.16.0) and alt (0.18.1).  Alt works fine without alt/utils but when I try to use the 'alt/utils/..." decorators I run into this error:

![image](https://cloud.githubusercontent.com/assets/1078376/11768880/56b36280-a1a8-11e5-81e8-678ad28e7277.png)

I don't even know what webpack is so I'm not sure where to specify the 'react': 'react-native' alias.

**Comment by goatslacker** [comment]
I believe its `require('alt/utils/lib/connectToStores')`

There's this though: https://github.com/altjs/react

**Comment by jnelken** [comment]
Looking through my web and mobile app alt node_modules, I see that the appropriate`alt/utils` files exist in ^0.17.0 but not in ^0.18.5 (on my react-native app). Using `npm install alt-utils` with the path `alt-utils/lib/...` fixed this for me when importing connectToStores.
