### ISSUE TITLE
alt-with-addons issues in AMD modules

### ISSUE THREAD

**Issue by hipertracker** [goatslacker/alt#345]
I am using [babel-requirejs](https://github.com/hipertracker/requirejs-babel) for having ES6 syntax and modules for my AMD modules. I've loaded Alt from the Bower but something was wrong. I mean,  the file `dist/alt-with-addons.js` does not seem to be built correctly. It assumes React is global rather than the UMD module. It is not clear how to use mentioned addons. E.g. how to import  `connectToStores` from `alt-with-addons.js`? That file seems to be built in the wrong way. Maybe it would be better to use Webpack to build the correct UMD module?

**Comment by goatslacker** [comment]
Leaving this here in case other people stumble upon this:

`Alt.addons.withAltContext`

**Comment by hipertracker** [comment]
The problem is alt-with-addons.js needs React defined globally. It does not work  with React loaded by AMD. That's known bug in Browserify. It has a  problem with loading packages with format "foo/bar" (e.g. "react/addons"). 

There are few solutions for that:

  1.  (ugly and current) - adding React as global before requirejs is load and do not import React inside modules 

  2.  (ugly and needs addidtional change to minified version) - patching by adding two lines to generated `alt-with-addons.js` file

    ```if (typeof React === 'undefined') React = require('react'); // PATCH @ line 112```

    ```if (typeof React === 'undefined')  _react = require('react'); // PATCH @ line 2982```

  3. (the best) **adding `--ignore-missing` to browserify** and rebuilding dist/*.  package.json#48 should be:

   ```
    "build-alt-browser-with-addons": "browserify src/alt/addons.js -t [envify --NODE_ENV production ] -t babelify -t browserify-shim --outfile dist/alt-with-addons.js --ignore-missing --standalone Alt",
  ```

  4. replacing   Browserify with  Webpack which should not have such problems

**Comment by hipertracker** [comment]
Unfortunately, point 3 (using `--ignore-missing`) does not solve the problem (there is one line still trying to find React in the global namespace)I think, the best option might to rebuild that file with Webpack.

**Comment by goatslacker** [comment]
I'm not opposed.

**Comment by goatslacker** [comment]
Here's a starting point: #222 I'm no webpack expert so someone is free to tackle this.

**Comment by hipertracker** [comment]
I found the line guilty of lats error. Alt is loading React  one place as  `import React from 'react/addons` and [in another place](https://github.com/goatslacker/alt/blob/master/src/utils/connectToStores.js#L46) as `import React from 'react'`. This is confusing for browserify. After change to 'read/addons' and adding `--ignore-missing` I have no error for using `var connectToStores = Alt.addons.connectToStores` but who know if the same problem can raise in another case... So switching to Webpack seems to be the good choice.

**Comment by goatslacker** [comment]
makes sense. Although I'm supposed to ignore react and react/addons

**Comment by hipertracker** [comment]
This webpack.config.js works for me:

```javascript
module.exports = {
  context: __dirname + '/src',
  entry: {
    'alt': ['./alt/index.js'],
    'alt-with-addons': ['./alt/addons.js']
  },
  output: {
    path: __dirname + '/dist',
    filename: '[name].js',
    library: 'Alt',
    libraryTarget: 'umd'
  },
  module: {
    loaders: [{
      test: /\.js$/,
      loader: 'babel',
      exclude: /node_modules/
    }]
  }
};
```

**Comment by goatslacker** [comment]
Want to create a PR based off that branch?

**Comment by hipertracker** [comment]
OK

**Comment by hipertracker** [comment]
I think  it would be good to fix two unit tests errors first. It happens when I run `npm install` on master or webpack branch:
```
  1)  the actions get the alt instance:
     AssertionError: alt is an instance of Alt: expected undefined to be an instance of Alt
      at ActionsGenerator.MyActions (test/stores-get-alt.js:20:16)
      at new ActionsGenerator (lib/index.js:139:104)
      at lib/index.js:162:30
      at Alt.createActions (lib/index.js:163:10)
      at Context.theActionsGetTheAltInstance (test/stores-get-alt.js:24:9)

  2) decorators decorating actions with args:
     AssertionError: expected undefined to be a function
      at Context.decoratingActionsWithArgs (test/decorators-test.js:59:14)
```
