### ISSUE TITLE
FluxyMixin not found for todomvc example

### ISSUE THREAD

**Issue by alansouzati** [goatslacker/alt#559]
I'm trying to test the todomvc example, but after cloning the latest alt and trying to run the todomvc example I get the following issue:

```bash
Error: module "../../../../mixins/FluxyMixin" not found from "/Users/alansouza/opensource-workspace/alt/examples/todomvc/js/components/TodoApp.react.js"
    at notFound (/Users/alansouza/opensource-workspace/alt/examples/todomvc/node_modules/browserify/index.js:812:15)
    at /Users/alansouza/opensource-workspace/alt/examples/todomvc/node_modules/browserify/index.js:762:23
    at /Users/alansouza/opensource-workspace/alt/examples/todomvc/node_modules/browser-resolve/index.js:264:24
    at /Users/alansouza/opensource-workspace/alt/examples/todomvc/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:18
    at load (/Users/alansouza/opensource-workspace/alt/examples/todomvc/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/alansouza/opensource-workspace/alt/examples/todomvc/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/alansouza/opensource-workspace/alt/examples/todomvc/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

I can't seem to find the mixins folder anymore. I'm assuming you guys removed mixins for ES6 support, but this example seems outdated then.

**Comment by goatslacker** [comment]
The mixins were actually just moved elsewhere: https://github.com/altjs/mixins I've removed the examples from this repo and will just be putting them elsewhere.
