### ISSUE TITLE
Documentation needs to be fixed

### ISSUE THREAD

**Issue by ankush17star** [goatslacker/alt#730]
The Getting Started guide is very misleading right at the beginning of one of the steps: http://alt.js.org/guide/actions/

Apparently, classes are not supported natively and only ES5 style works

This kind of unexpected result may put off some new users

If you run the **exact** code on the webpage (and there's not a whole lot to it), it returns:
```
TypeError: Class constructor LocationActions cannot be invoked without 'new'
    at new ActionsGenerator (<path>/node_modules/alt/lib/index.js:187:72)
    at Alt.createActions (<path>/node_modules/alt/lib/index.js:211:28)
    at Object.<anonymous> (<path>/actions/locations.js:9:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

It **needs** to say that the ES6 classes **need** to be transpiled into the ES5 format''

Granted that happens automatically in the build tools, but for first-timers, things appear broken (if we run them without transpiling)

**Comment by 3dfoster** [comment]
I went through this issue going through the getting started guide and I don't know how to fix it

**Comment by ankush17star** [comment]
Hi @fasterthan

The fix is to transpile the code to an ES5 version

You can use Babel or an online tool for it. E.g [Online Transpiler](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAhjAvDAFASiQPhgbwFAwyiQgA2ApgHSkgDmKA5ABICWDaeAvkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.5.5&externalPlugins=)

**Comment by 3dfoster** [comment]
Hey @ankush17star

Thanks, I tried that but it's getting hung up on the line `module.exports = alt.createActions(LocationActions);` in **LocationActions.js**, throwing the error `×
TypeError: Class constructor LocationStore cannot be invoked without 'new'`.

**Comment by ankush17star** [comment]
@fasterthan Can you share your code sample here please? I'll take a look and get back to you

**Comment by maheshambiga** [comment]
I am still getting the below error though I am using babel to transpire.
`TypeError: Class constructor TodoActions cannot be invoked without 'new'`
